HORNMOD_AddHorns({name = "sfx_v4cpau", info = "FUCKIN' QUEERS", extags = "queers"})
HORNMOD_AddHorns({name = "sfx_v4cnig", info = "nigger"})
HORNMOD_AddHorns({name = "sfx_v4cnaw", info = "Hell naw"})
HORNMOD_AddHorns({name = "sfx_v4ccum", info = "I'M CUMMIN - Alex Jones"})
HORNMOD_AddHorns({name = "sfx_v4coom", info = "I'M GONNA COOM"})
HORNMOD_AddHorns({name = "sfx_v4cwrt", info = "Wort wort wort - halo"})
HORNMOD_AddHorns({name = "sfx_v4cmin", info = "Minecraft oof"})
HORNMOD_AddHorns({name = "sfx_v4cwol", info = "Wololo - AoE"})
HORNMOD_AddHorns({name = "sfx_v4cscm", info = "Vergil SCHUM"})
HORNMOD_AddHorns({name = "sfx_v4caaa", info = "AAAAAAAAAAA - Jet Set Radio"})
HORNMOD_AddHorns({name = "sfx_v4caug", info = "Puffer Fish Augh"})
HORNMOD_AddHorns({name = "sfx_v4cbup", info = "Bird Up"})
HORNMOD_AddHorns({name = "sfx_v4cbof", info = "Boffa"})
HORNMOD_AddHorns({name = "sfx_v4cbro", info = "Brotherman Bill"})
HORNMOD_AddHorns({name = "sfx_v4cdan", info = "VOTE DANIEL"})
HORNMOD_AddHorns({name = "sfx_v4ceee", info = "Ed Edd and Eddy Horn"})
HORNMOD_AddHorns({name = "sfx_v4cgal", info = "GO"})
HORNMOD_AddHorns({name = "sfx_v4cgra", info = "Grabba"})
HORNMOD_AddHorns({name = "sfx_v4cgor", info = "Hello Gordon"})
HORNMOD_AddHorns({name = "sfx_v4ctru", info = "I don't trust like that"})
HORNMOD_AddHorns({name = "sfx_v4cjes", info = "Kill Jestah"})
HORNMOD_AddHorns({name = "sfx_v4clig", info = "Ligma"})
HORNMOD_AddHorns({name = "sfx_v4cmsw", info = "Gundam ms warning"})
HORNMOD_AddHorns({name = "sfx_v4cgno", info = "Mystery Horn", extags = "gnome"})
HORNMOD_AddHorns({name = "sfx_v4cjon", info = "John - DIVORCE"})
HORNMOD_AddHorns({name = "sfx_v4cosh", info = "OH SHIT"})
HORNMOD_AddHorns({name = "sfx_v4cspl", info = "Sploosh"})
HORNMOD_AddHorns({name = "sfx_v4cnuk", info = "Tactical nuke"})
HORNMOD_AddHorns({name = "sfx_v4cche", info = "Chen honk"})
HORNMOD_AddHorns({name = "sfx_v4ctre", info = "Treason"})
HORNMOD_AddHorns({name = "sfx_v4ctut", info = "Tuturuu"})
HORNMOD_AddHorns({name = "sfx_v4cale", info = "You're not Alexander"})
HORNMOD_AddHorns({name = "sfx_v4ccla", info = "Berserk Clang"})
HORNMOD_AddHorns({name = "sfx_v4cfag", info = "Coyle - Power tripping fucking FAGGOT"})
HORNMOD_AddHorns({name = "sfx_v4cfbt", info = "Go on and die you fat bitch"})
HORNMOD_AddHorns({name = "sfx_v4cgmd", info = "God motherfucking damn"})
HORNMOD_AddHorns({name = "sfx_v4caus", info = "IT'S ME AUSTIN"})
HORNMOD_AddHorns({name = "sfx_v4cchu", info = "Vitas - Chum Drum Bedrum"})
HORNMOD_AddHorns({name = "sfx_v4cmms", info = "Meet me somewhere"})
HORNMOD_AddHorns({name = "sfx_v4cnir", info = "Nigga racer"})
HORNMOD_AddHorns({name = "sfx_v4cnos", info = "Noscope"})
HORNMOD_AddHorns({name = "sfx_v4cnwf", info = "No way fag"})
HORNMOD_AddHorns({name = "sfx_v4cput", info = "POOTIS"})
HORNMOD_AddHorns({name = "sfx_v4csen", info = "DON'T FUCK WITH THIS SENATOR"})
HORNMOD_AddHorns({name = "sfx_v4csmn", info = "Sup my nigga"})
HORNMOD_AddHorns({name = "sfx_v4csbb", info = "Supadebadboy"})
HORNMOD_AddHorns({name = "sfx_v4cpan", info = "TF2 Frying Pan"})
HORNMOD_AddHorns({name = "sfx_v4cvgb", info = "I am a very good bad boy", extags="badboy"})

--ripandtear horns
HORNMOD_AddHorns({name = "sfx_v4c4uu", info = "4U"})
HORNMOD_AddHorns({name = "sfx_v4c15m", info = "15 MILES"})
HORNMOD_AddHorns({name = "sfx_v4c900", info = "900 DOLLARYDOOS"})
HORNMOD_AddHorns({name = "sfx_v4calo", info = "ALOHA"})
HORNMOD_AddHorns({name = "sfx_v4caug", info = "NerdGasm", extags = "leather belt"})
HORNMOD_AddHorns({name = "sfx_v4cbal", info = "Ballin"})
HORNMOD_AddHorns({name = "sfx_v4cbat", info = "GO AWAY BAIT'N"})
HORNMOD_AddHorns({name = "sfx_v4cbeg", info = "It Begins"})
HORNMOD_AddHorns({name = "sfx_v4cbig", info = "You're a big guy", extags = "Big guy"})
HORNMOD_AddHorns({name = "sfx_v4cbob", info = "Bob Saget"})
HORNMOD_AddHorns({name = "sfx_v4cbod", info = "Bodyshot"})
HORNMOD_AddHorns({name = "sfx_v4cbos", info = "Balls of Steel"})
HORNMOD_AddHorns({name = "sfx_v4cbwa", info = "B'wah"})
HORNMOD_AddHorns({name = "sfx_v4ccok", info = "Word around the office"})
HORNMOD_AddHorns({name = "sfx_v4cdel", info = "Deel'doh"})
HORNMOD_AddHorns({name = "sfx_v4cdic", info = "DIC"})
HORNMOD_AddHorns({name = "sfx_v4cdie", info = "die"})
HORNMOD_AddHorns({name = "sfx_v4cdik", info = "Dick Sale"})
HORNMOD_AddHorns({name = "sfx_v4cdis", info = "DISGOOSTAN"})
HORNMOD_AddHorns({name = "sfx_v4cdog", info = "Finddog"})
HORNMOD_AddHorns({name = "sfx_v4cdoo", info = "Dododododooo"})
HORNMOD_AddHorns({name = "sfx_v4cfat", info = "HE'S FAT"})
HORNMOD_AddHorns({name = "sfx_v4cfg2", info = "Faggots"})
HORNMOD_AddHorns({name = "sfx_v4cfuh", info = "Buenos Noches Mein Fuhrer"})
HORNMOD_AddHorns({name = "sfx_v4cgab", info = "Gaben"})
HORNMOD_AddHorns({name = "sfx_v4cgrm", info = "SHUTTUP GRAMMA"})
HORNMOD_AddHorns({name = "sfx_v4chod", info = "Hood"})
HORNMOD_AddHorns({name = "sfx_v4choh", info = "Hohohohoho"})
HORNMOD_AddHorns({name = "sfx_v4chur", info = "Tim Allen Grunt"})
HORNMOD_AddHorns({name = "sfx_v4chyg", info = "Hey G"})
HORNMOD_AddHorns({name = "sfx_v4cilr", info = "Ilikerape"})
HORNMOD_AddHorns({name = "sfx_v4cjca", info = "JC a bomb"})
HORNMOD_AddHorns({name = "sfx_v4ckra", info = "Kramer at the laugh factory"})
HORNMOD_AddHorns({name = "sfx_v4cm16", info = "I carried an M16"})
HORNMOD_AddHorns({name = "sfx_v4cmay", info = "Billy Mays"})
HORNMOD_AddHorns({name = "sfx_v4cmcd", info = "RockDonalds"})
HORNMOD_AddHorns({name = "sfx_v4cmed", info = "MEDIUM LEFT"})
HORNMOD_AddHorns({name = "sfx_v4cmje", info = "Mormon Jesus"})
HORNMOD_AddHorns({name = "sfx_v4cmmm", info = "Morshu MMMMMM"})
HORNMOD_AddHorns({name = "sfx_v4cnoh", info = "Noh"})
HORNMOD_AddHorns({name = "sfx_v4cohn", info = "OH NO Jojo"})
HORNMOD_AddHorns({name = "sfx_v4cohs", info = "Oh Snap"})
HORNMOD_AddHorns({name = "sfx_v4comg", info = "Oh my gah"})
HORNMOD_AddHorns({name = "sfx_v4cooo", info = "OOOOOOOOOO"})
HORNMOD_AddHorns({name = "sfx_v4cori", info = "Baltimore Orioles"})
HORNMOD_AddHorns({name = "sfx_v4cpub", info = "Pubfag"})
HORNMOD_AddHorns({name = "sfx_v4crmb", info = "Rattlemebones"})
HORNMOD_AddHorns({name = "sfx_v4csdc", info = "Your Soundcard"})
HORNMOD_AddHorns({name = "sfx_v4cstk", info = "DOOR STUCK"})
HORNMOD_AddHorns({name = "sfx_v4cstp", info = "Stahp It"})
HORNMOD_AddHorns({name = "sfx_v4ctod", info = "Toad Scream"})
HORNMOD_AddHorns({name = "sfx_v4cttt", info = "Triple Caution"})
HORNMOD_AddHorns({name = "sfx_v4cweo", info = "WEEWOO"})
HORNMOD_AddHorns({name = "sfx_v4cwow", info = "wow"})
HORNMOD_AddHorns({name = "sfx_v4cwwy", info = "When will you learn?"})
HORNMOD_AddHorns({name = "sfx_v4cyah", info = "Yah"})
HORNMOD_AddHorns({name = "sfx_v4cyff", info = "You Fricken Fricks"})