--November Horns
HORNMOD_AddHorns({name = "sfx_2016GH", info = "2016"})
HORNMOD_AddHorns({name = "sfx_HBDHYB", info = "Ainsley Hyeah boi"})
HORNMOD_AddHorns({name = "sfx_ALLAHU", info = "ALLAH ACKBAR"})
HORNMOD_AddHorns({name = "sfx_SOUNDB", info = "APROACHING SOUND BARRIER"})
HORNMOD_AddHorns({name = "sfx_BASED0", info = "BASED BASED BASED"})
HORNMOD_AddHorns({name = "sfx_SSGHSE", info = "BBQ Pit Boys", extags = "House of Sausage"})
HORNMOD_AddHorns({name = "sfx_BEKFST", info = "Bekfast"})
HORNMOD_AddHorns({name = "sfx_BOIIFY", info = "BOI IF YOU DON'T"})
HORNMOD_AddHorns({name = "sfx_BONKST", info = "bonk"})
HORNMOD_AddHorns({name = "sfx_HBDBKL", info = "Burger King Foot Lettuce"})
HORNMOD_AddHorns({name = "sfx_BYEAHS", info = "byeah"})
HORNMOD_AddHorns({name = "sfx_HBDCBT", info = "CBT"})
HORNMOD_AddHorns({name = "sfx_HBCHOC", info = "CHOCOLATE"})
HORNMOD_AddHorns({name = "sfx_DZNUTS", info = "Deez Nuts", extags = "Goteem"})
HORNMOD_AddHorns({name = "sfx_DOINGR", info = "doin"})
HORNMOD_AddHorns({name = "sfx_v4cqua", info = "Duck"})
HORNMOD_AddHorns({name = "sfx_FART01", info = "fart"})
HORNMOD_AddHorns({name = "sfx_v4cfhr", info = "FHRITP"})
HORNMOD_AddHorns({name = "sfx_FREAKR", info = "Freddy Freaker"})
HORNMOD_AddHorns({name = "sfx_BALTIM", info = "FUCK YOU BALTIMORE"})
HORNMOD_AddHorns({name = "sfx_HBDHTL", info = "Gachi Scream"})
HORNMOD_AddHorns({name = "sfx_HAMOO2", info = "Hamood Hamood"})
HORNMOD_AddHorns({name = "sfx_HRPSEL", info = "Harp Seal"})
HORNMOD_AddHorns({name = "sfx_CANTBL", info = "I can't believe you've done this"})
HORNMOD_AddHorns({name = "sfx_FCKBEE", info = "IT'S HIP TO FUCK BEES"})
HORNMOD_AddHorns({name = "sfx_LGOHEY", info = "Lego HEY"})
HORNMOD_AddHorns({name = "sfx_LGOYDA", info = "Lego Yoda"})
HORNMOD_AddHorns({name = "sfx_LTSGOO", info = "LETS FUCKING GOOOOOOOOOOOOOOOOO"})
HORNMOD_AddHorns({name = "sfx_HBDLN1", info = "Loud Nigra 1"})
HORNMOD_AddHorns({name = "sfx_HBDLN2", info = "Loud Nigra 2"})
HORNMOD_AddHorns({name = "sfx_HBDPGU", info = "Noot Noot"})
HORNMOD_AddHorns({name = "sfx_COOMIN", info = "OH GOD IM COOMING"})
HORNMOD_AddHorns({name = "sfx_DATBO2", info = "OHSHIT whaddup", extags = "datboi"})
HORNMOD_AddHorns({name = "sfx_NODAIP", info = "Poop in pants no diaper"})
HORNMOD_AddHorns({name = "sfx_JMPPEE", info = "Poopoo Peepee"})
HORNMOD_AddHorns({name = "sfx_v4crat", info = "RunForTheCube Hello"})
HORNMOD_AddHorns({name = "sfx_HBSTFU", info = "Shut the fuck up"})
HORNMOD_AddHorns({name = "sfx_SPIDEY", info = "Spiderman"})
HORNMOD_AddHorns({name = "sfx_CRECRO", info = "The cream of the crop"})
HORNMOD_AddHorns({name = "sfx_FKNGAY", info = "Traps"})
HORNMOD_AddHorns({name = "sfx_UFOPRN", info = "UFOPORNO"})
HORNMOD_AddHorns({name = "sfx_UHOHST", info = "Uh Oh, Stinky!"})
HORNMOD_AddHorns({name = "sfx_CRCKL5", info = "YOU CAN SUCK MY D"})
HORNMOD_AddHorns({name = "sfx_JOKERQ", info = "YOU GET WHAT YOU FUCKING DESERVE"})
HORNMOD_AddHorns({name = "sfx_SUKCLN", info = "YOU'RE GONNA SUCK THIS COCK CLEAN"})
HORNMOD_AddHorns({name = "sfx_B17BOM", info = "B-17 Bomber"})
HORNMOD_AddHorns({name = "sfx_GAWSBS", info = "Ghostbusters"})
HORNMOD_AddHorns({name = "sfx_HBDMMF", info = "MAMA F*CKER"})
HORNMOD_AddHorns({name = "sfx_HBDMOF", info = "Mario OOF"})
HORNMOD_AddHorns({name = "sfx_MARSC1", info = "MARIO SCREAMING"})
HORNMOD_AddHorns({name = "sfx_HBHYLP", info = "Mama Luigi HELP"})
HORNMOD_AddHorns({name = "sfx_GAYLUG", info = "Gay Luigi"})
HORNMOD_AddHorns({name = "sfx_DOHIEC", info = "DOH I MISSED"})
HORNMOD_AddHorns({name = "sfx_WARDIE", info = "Wario Dies"})
HORNMOD_AddHorns({name = "sfx_WARIGO", info = "Wario GO"})
HORNMOD_AddHorns({name = "sfx_COLBNA", info = "Oh these are pretty cool bananas"})
HORNMOD_AddHorns({name = "sfx_HBDBMB", info = "Morshu Bombs?"})
HORNMOD_AddHorns({name = "sfx_HBDGRE", info = "CDi Link Great"})
HORNMOD_AddHorns({name = "sfx_HBDYWD", info = "You will DIE"})
HORNMOD_AddHorns({name = "sfx_HBDOAH", info = "CDi King Hoa"})
HORNMOD_AddHorns({name = "sfx_SHOWYA", info = "Show Me Ya Moves!"})
HORNMOD_AddHorns({name = "sfx_GUHHUH", info = "Banjo Guhhuh"})
HORNMOD_AddHorns({name = "sfx_HBDWMY", info = "Woomy"})
HORNMOD_AddHorns({name = "sfx_SQDKID", info = "YOU'RE A KID YOU'RE A SQUID"})
HORNMOD_AddHorns({name = "sfx_HBOHOH", info = "WOMBO COMBO"})
HORNMOD_AddHorns({name = "sfx_MSTRBN", info = "Sonic Masturbating"})
HORNMOD_AddHorns({name = "sfx_HBDOHN", info = "Knuckles Oh No"})
HORNMOD_AddHorns({name = "sfx_HBDOR9", info = "IT'S OVER 9000"})
HORNMOD_AddHorns({name = "sfx_HBDPGS", info = "Pingas"})
HORNMOD_AddHorns({name = "sfx_HBRBNO", info = "Robotnik NO"})
HORNMOD_AddHorns({name = "sfx_TOMORR", info = "Tomorrow I'll"})
HORNMOD_AddHorns({name = "sfx_COOLST", info = "I'm the coolest"})
HORNMOD_AddHorns({name = "sfx_HBGMOY", info = "GAME OVER YEAAAAAAAAAAH"})
HORNMOD_AddHorns({name = "sfx_CRAZYT", info = "Crazy Taxi"})
HORNMOD_AddHorns({name = "sfx_YAYAYA", info = "YA YA YA YA YA"})
HORNMOD_AddHorns({name = "sfx_UNDRST", info = "UNDERSTAND UNDERSTAND"})
HORNMOD_AddHorns({name = "sfx_BKAMIT", info = "Baka Mitai"})
HORNMOD_AddHorns({name = "sfx_FHBRTG", info = "BURN TO THE GROUND"})
HORNMOD_AddHorns({name = "sfx_FHBURN", info = "BURN"})
HORNMOD_AddHorns({name = "sfx_v4cron", info = "RULES OF NATURE"})
HORNMOD_AddHorns({name = "sfx_SEPCHI", info = "Sephiroth"})
HORNMOD_AddHorns({name = "sfx_TIDUSL", info = "Tidus Laugh"})
HORNMOD_AddHorns({name = "sfx_RUOKAY", info = "ARE YOU OKAY"})
HORNMOD_AddHorns({name = "sfx_HBDAYB", info = "All your base are belong to us"})
HORNMOD_AddHorns({name = "sfx_BIFFED", info = "Oh, I biffed it"})
HORNMOD_AddHorns({name = "sfx_HBDTST", info = "Toasty"})
HORNMOD_AddHorns({name = "sfx_HBDGBN", info = "Gaben"})
HORNMOD_AddHorns({name = "sfx_HLARGH", info = "Half Life Scientist - ARGH"})
HORNMOD_AddHorns({name = "sfx_HLECHH", info = "Half Life Scientist - ECHH"})
HORNMOD_AddHorns({name = "sfx_HLSTAP", info = "Half Life Scientist - STAP"})
HORNMOD_AddHorns({name = "sfx_FCDUMF", info = "You fucked up my face"})
HORNMOD_AddHorns({name = "sfx_CSBOMB", info = "Bomb has been planted"})
HORNMOD_AddHorns({name = "sfx_OUTTWA", info = "OUTTA MY WAY SON", extags = "I'M A RAISIN"})
HORNMOD_AddHorns({name = "sfx_BEGYOU", info = "I BEG YOU"})
HORNMOD_AddHorns({name = "sfx_GNUDKS", info = "GENUINE DICKSUCKER"})
HORNMOD_AddHorns({name = "sfx_v4cnop", info = "Nope.avi"})
HORNMOD_AddHorns({name = "sfx_ENGIDS", info = "Engineer dies"})
HORNMOD_AddHorns({name = "sfx_HBDGTM", info = "Gentlemen"})
HORNMOD_AddHorns({name = "sfx_HBDHLY", info = "Quake Holy Shit"})
HORNMOD_AddHorns({name = "sfx_v4cold", info = "Deus Ex Old Men"})
HORNMOD_AddHorns({name = "sfx_AUGVIS", info = "My vision is augmented"})
HORNMOD_AddHorns({name = "sfx_WATSHA", info = "What a Shame"})
HORNMOD_AddHorns({name = "sfx_v4cmur", info = "Murloc"})
HORNMOD_AddHorns({name = "sfx_FNDFDN", info = "Default Dance"})
HORNMOD_AddHorns({name = "sfx_CJSHIT", info = "CJ Oh Shit"})
HORNMOD_AddHorns({name = "sfx_DAMTRN", info = "ALL WE HAD TO DO WAS FOLLOW THE DAMN TRAIN CJ"})
HORNMOD_AddHorns({name = "sfx_KEEPUP", info = "Keep up motherfucka"})
HORNMOD_AddHorns({name = "sfx_ANOONE", info = "Another One"})
HORNMOD_AddHorns({name = "sfx_DOWNWI", info = "Down With The Sickness", extags = "OOH AH AH AH AH"})
HORNMOD_AddHorns({name = "sfx_ROLLIN", info = "Keep Rollin"})
HORNMOD_AddHorns({name = "sfx_OHSNAP", info = "Oh Snap!"})
HORNMOD_AddHorns({name = "sfx_RESES1", info = "REESES PUFFS REESES PUFFS"})
HORNMOD_AddHorns({name = "sfx_HBDHYN", info = "Smash Mouth - All Star"})
HORNMOD_AddHorns({name = "sfx_HBDYOU", info = "Soulja Boy YOUUUUUUUUUUUUU"})
HORNMOD_AddHorns({name = "sfx_SMOWEE", info = "Smoke Weed Everyday"})
HORNMOD_AddHorns({name = "sfx_MONKIF", info = "WOAH-OH-OH-AH-AH-AH-AAAA-HA-AH-AH-AH"})
HORNMOD_AddHorns({name = "sfx_DNSKTR", info = "Dinkster"})
HORNMOD_AddHorns({name = "sfx_CKNAGW", info = "Fesh Pince - Chicken and Wingish"})
HORNMOD_AddHorns({name = "sfx_JEFERY", info = "Fesh Pince - Geoffrey"})
HORNMOD_AddHorns({name = "sfx_GOTCHA", info = "Fesh Pince - GOTCHA"})
HORNMOD_AddHorns({name = "sfx_NUMBRS", info = "Fesh Pince - NUMBERS NUMBERS"})
HORNMOD_AddHorns({name = "sfx_PZAHUT", info = "Fesh Pince - Pizza Hut in the Garage"})
HORNMOD_AddHorns({name = "sfx_SWNDLD", info = "Fesh Pince - You swindled me"})
HORNMOD_AddHorns({name = "sfx_HBDDOI", info = "Sheev Do It"})
HORNMOD_AddHorns({name = "sfx_SLDOIT", info = "Shia Do It"})
HORNMOD_AddHorns({name = "sfx_SCKANM", info = "SickAnimations"})
HORNMOD_AddHorns({name = "sfx_HBDSRT", info = "Suckin on Raphie's Toes"})
HORNMOD_AddHorns({name = "sfx_FCKNJT", info = "www.ifuckninjaturtles.uk", extags = "Green Lovers"})
HORNMOD_AddHorns({name = "sfx_GOOFYL", info = "Goofy scream"})
HORNMOD_AddHorns({name = "sfx_TOMSCR", info = "Tom Scream"})
HORNMOD_AddHorns({name = "sfx_NUTSHA", info = "It's The Nutshack"})
HORNMOD_AddHorns({name = "sfx_HUUAGH", info = "The Nutshack - HUUAGH"})
HORNMOD_AddHorns({name = "sfx_TITODK", info = "The Nutshack - Tito"})
HORNMOD_AddHorns({name = "sfx_HBDFWM", info = "Have some fun with Miku"})
HORNMOD_AddHorns({name = "sfx_HESGOI", info = "He's going over that cliff"})
HORNMOD_AddHorns({name = "sfx_HBDNAA", info = "Nanachi Naa"})
HORNMOD_AddHorns({name = "sfx_RUN90s", info = "Running In The 90s"})
HORNMOD_AddHorns({name = "sfx_WRYYYY", info = "WRYYYYYYYYYYYYYYYYYYY"})
HORNMOD_AddHorns({name = "sfx_HBDYAY", info = "Yay", extags = "Yey"})
HORNMOD_AddHorns({name = "sfx_OMAEWA", info = "You are already dead"})
